[package]
name = "pumpkin"
version = "0.1.0-dev"
description = "Empowering everyone to host fast and efficient Minecraft servers."
edition = "2021"

[features]
default = ["plugins"]
plugins = ["pumpkin-plugin/plugins"]

[dependencies]
# pumpkin
pumpkin-core = { path = "../pumpkin-core"}
pumpkin-config = { path = "../pumpkin-config" }
pumpkin-plugin = { path = "../pumpkin-plugin"}
pumpkin-inventory = { path = "../pumpkin-inventory"}
pumpkin-world = { path = "../pumpkin-world"}
pumpkin-entity = { path = "../pumpkin-entity"}
pumpkin-protocol = { path = "../pumpkin-protocol"}
pumpkin-registry = { path = "../pumpkin-registry"}

itertools = "0.13.0"

# config
serde.workspace = true
serde_json = "1.0"

bytes = "1.7"

rand = "0.8.5"

num-traits = "0.2"
num-derive = "0.4"
num-bigint = "0.4"

ctrlc = "3.4"

# encryption
rsa = "0.9.6"
rsa-der = "0.3.0"

# authentication
reqwest = { version = "0.12.7", default-features= false, features = ["json", "rustls-tls", "http2", "macos-system-configuration"]}

sha1 = "0.10.6"
digest = "=0.11.0-pre.9"

# velocity en
hmac = "0.12.1"
sha2 = "0.10.8"

thiserror = "1.0"

# icon loading
base64 = "0.22.1"
image = { version = "0.25", default-features = false, features = ["png"]}

# logging
simple_logger = "5.0.0"
log.workspace = true

parking_lot.workspace = true
crossbeam.workspace = true
uuid.workspace = true
tokio.workspace = true
rayon.workspace = true
